### ISSUE TITLE
iPadでのアプリダウンロードの問題

### ISSUE THREAD

**Issue by Zaki-XL** [KLab/emlauncher#8]
create install tokenでアプリケーションをダウンロードするときの問題です

こちらmfwフレームワークでOSの判定をしておりますがiOS 13からSafariのユーザーエージェントが変更になったため、iOSとして認識できなくなりました

https://github.com/makiuchi-d/mfw/blob/162103735360639dd626bb27fc0ef8a2a7c1066d/Request/mfwUserAgent.php

```
iOS12
Mozilla/5.0 (iPad; CPU OS 12_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1
```

```
iOS13
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15
```

対応方針としては、下記方針が考えられると思います

* デフォルトをiOSとして扱い、未定義をiPadとして扱う
* Apacheなどで無理やりユーザーエージェントを書き換える(判定方法がないような気もしますが)
* iPadのSafariの設定を変更し、モバイルとして認識させる

要は「フレームワーク側でiPadとして認識するように対応する」か、「フロントまたはクライアント側で対応する」のどちらの方針にするのかをご教授いただけますでしょうか

**Comment by makiuchi-d** [comment]
報告ありがとうございます。応答がおそくなりすみません。

この現象ですが、iPadのユーザーエージェントが変更されたわけではなく、Safariの設定の「デスクトップ用Webサイトを表示」がデフォルトで有効になったためです。
このときのユーザーエージェントはmacOSのSafariと同じため、iPadとして扱ってしまうとMacでipaファイルをダウンロードできなくなってしまいます。

サーバサイドでの確実な判定は難しいため、iPadのSafariで「モバイル用Webサイトを表示」することをおすすめします。
これによりこれまで通りiPadとして認識されるようになります。

**Comment by Zaki-XL** [comment]
ありがとうございます。クライアントサイドで対応するという方針で了解しました

なお、ブラウザの枠を補足するとUserAgerntが変わって「iPad」と言う文字列が出てくるので判定できる、というワークラウンドもあります（正直ブラウザ枠の幅がかわるだけでUAが変わるってどういうことなんだとは思いますが…）
